### ISSUE TITLE
Error while running Tests for PingPong

### ISSUE THREAD

**Issue by v13s** [hyperledger-labs/fabric-smart-client#70] opened 2021-07-05 18:18 UTC
I am new to fabric-smart-client. I was trying out he PingPong on my VM with following details:
OS: Ubuntu 18 VM.
+ Go version go1.14.6 linux/amd64
+ build-essential
+ fabric-smart-client cloned at  /home/ubuntu, 

I executed the 'go test' command at path /home/ubuntu/fabric-smart-client/integration/fsc/pingpong

Error Received:

```
Summarizing 3 Failures:

[Panic!] EndToEnd Network-based Ping pong [It] generate artifacts & successful pingpong
/home/ubuntu/fabric-smart-client/integration/integration.go:209

[Panic!] EndToEnd Network-based Ping pong [It] generate artifacts & successful pingpong with Admin
/home/ubuntu/fabric-smart-client/integration/integration.go:209

[Panic!] EndToEnd Network-based Ping pong [It] load artifact & successful pingpong
/home/ubuntu/fabric-smart-client/integration/integration.go:209

```
[errorlog.txt](https://github.com/hyperledger-labs/fabric-smart-client/files/6765849/errorlog.txt)

**Comment by adecaro** [comment] 2021-07-06 04:05
Hi @v13s ,

Looking at the logs, the problem seems related to setting properly your GOPATH/GOROOT first.

 ```can't load package: package home/ubuntu/fabric-smart-client/integration/fsc/pingpong/cmd/responder is not in GOROOT (/usr/local/go/src/home/ubuntu/fabric-smart-client/integration/fsc/pingpong/cmd/responder)```

Where did you set it?

**Comment by v13s** [comment] 2021-07-06 09:09
Hi @adecaro, please find below the environment variables. 

HOME=/root
LANG=C.UTF-8
GOROOT=/usr/local/go
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:/bin
GOPATH=/home/ubuntu:/root/go

**Comment by adecaro** [comment] 2021-07-06 09:17
I think this is related to a mismatch between GOPATH and GOROOT. Set the GOPATH to just one folder and have empty GOROOT. 
The issue is not related to the smart client per se. You must have a properly set go env in your system. Please, refer to the go documentation for that. Thanks.

**Comment by v13s** [comment] 2021-07-06 16:15
It does not seem specific to my environment as its a new VM and I have repeated the same with multiple configurations and did not work.

There must be some specific step which is missing in the client documentation or minor error.

**Comment by adecaro** [comment] 2021-07-06 16:51
As you can check by yourself our CI is working fine. I would bet that it is your go environment that is not probably set but I might be wrong. 

If you are okay, I would close this issue cause it does not seem related to the smart client per se. What do you think?

**Comment by v13s** [comment] 2021-07-07 05:49
Sure. No worries. 

However, I still believe that issue must be specific for fabric-smart-client, GO configuration required here is different from what is generally required. 

Specially given that we use GO lang for Fabric Chaincodes & stuff and I have configured it accordingly. Its more like a script that I have been using for a while to setup Go. 

One more thing, it may be nothing but If you go to https://github.com/hyperledger-labs/fabric-smart-client/tree/main/integration/fsc/pingpong, you will find that there is only cmd/initiator, and cmd/responder is not there. It gets generated afterwards when you run 'go test', may be that is why it is different and causes the issue.

**Comment by adecaro** [comment] 2021-07-07 12:43
Just executed the tests on my machine using `go test` as you did:
```Ran 5 of 5 Specs in 96.791 seconds
SUCCESS! -- 5 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS
ok      github.com/hyperledger-labs/fabric-smart-client/integration/fsc/pingpong        97.596s
```

Also the CI is passing and the CI uses the GO env as setup by github action. 
This is the reason why I don't see what can be wrong on the smart client but I might miss something.

**Comment by v13s** [comment] 2021-07-10 14:22
Thanks @adecaro , for your efforts and bearing with me. Can you please share the environment variables from your machine and also the git clone directory. That would be a great help. Post that feel free to close the issue. I'll try to investigate further based on your input.

**Comment by adecaro** [comment] 2021-07-11 06:56
@v13s, I kept trying and with Docker I managed to reproduce your environment and get the same error. Let me see how this can be fixed and I will come back to you. Thanks a lot for your valuable feedback :)

**Comment by adecaro** [comment] 2021-07-11 08:24
So, using this Dockerfile, it works:
```
FROM golang:1.14.15

WORKDIR /go/src/github.com/hyperledger-labs/
RUN git clone https://github.com/hyperledger-labs/fabric-smart-client.git
WORKDIR ./fabric-smart-client/integration/fsc/pingpong
RUN go test
```
`/go` is the GOPATH, and instead of cloning under `/go`, I have cloned under `/go/src/github.com/hyperledger-labs/`.
So, it is as you said, because of the node's main is generated on the fly, it is expected to be found in a certain location.

**Comment by v13s** [comment] 2021-07-11 14:24
Thanks @adecaro. appreciate your help, support and commitment. Please feel free to close this issue. I tried the same and worked for me too. 

This issue here will definitely help many new users as are likely to face this issue, unless we update the documentation.

**Closed** 2021-07-13 09:25 UTC
